export const CATEGORIES = [
  {
    "category": "Fashion",
    "subcategory": [
      "Bloggers",
      "Photographers",
      "Designers",
      "Models",
      "Stylists",
      "Influencers",
      "Journalists",
      "Consultants",
      "Retailers",
      "Photographers",
    ],
  },
  {
    "category": "Beauty",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Makeup Artists",
      "Product Reviewers",
    ],
  },
  {
    "category": "Food",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Chefs",
      "Product Reviewers",
    ],
  },
  {
    "category": "Travel",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Agents",
      "Product Reviewers",
    ],
  },
  {
    "category": "Sports",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Coaches",
      "Product Reviewers",
    ],
  },
  {
    "category": "Lifestyle",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Coaches",
      "Product Reviewers",
    ],
  },
  {
    "category": "Technology",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Developers",
      "Product Reviewers",
    ],
  },
  {
    "category": "Entertainment",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Actors",
      "Actresses",
      "Product Reviewers",
    ],
  },
  {
    "category": "Health & Fitness",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Coaches",
      "Trainers",
      "Instructors",
      "Gurus",
      "Experts",
      "Nutritionists",
      "Dietitians",
      "Therapists",
      "Physicians",
      "Surgeons",
      "Specialists",
      "Clinicians",
      "Researchers",
      "Scientists",
      "Professors",
      "Teachers",
      "Instructors",
      "Mentors",
      "Mentees",
      "Mentorships",
      "Mentoring Programs",
      "Mentoring Services",
      "Mentoring Organizations",
      "Mentoring Platforms",
      "Mentoring Communities",
      "Mentoring Networks",
      "Mentoring Initiatives",
      "Mentoring Projects",
      "Mentoring Events",
      "Mentoring Conferences",
      "Mentoring Workshops",
    ],
  },
  {
    "category": "Business",
    "subcategory": [
      "Bloggers",
      "Vloggers",
      "Photographers",
      "Influencers",
      "Consultants",
      "Retailers",
      "Journalists",
      "Stylists",
      "Entrepreneurs",
      "Founders",
      "CEOs",
      "CFOs",
      "COOs",
      "CMOs",
      "CTOs",
      "CIOs",
      "CDOs",
      "CXOs",
      "C-Suite Executives",
      "Leaders",
      "Strategists",
      "Analysts",
      "Advisors",
      "Coaches",
      "Mentors",
      "Trainers",
      "Speakers",
      "Writers",
      "Authors",
      "Educators",
      "Facilitators",
      "Moderators",
      "Facilitators and Moderators",
    ],
  },
];
