name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx affected --target=lint --parallel=3
      - run: npm nx affected:apps
#       - run: npx nx run-many --target=build --projects=shell,api --parallel=2
#       - run: bash scripts/pipeline/release.sh ${{secrets.AWS_Bucket_Name}} "flenzr.zip" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "dist/*"
