name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npm run build:prod:shell
      - run: ls -ltar dist/apps
      - name: Release to S3
      - run: bash scripts/pipeline/release.sh ${{secrets.AWS_Bucket_Name}} "shell" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "dist/apps/shell"
